# Generated by Django 3.0.5 on 2020-11-28 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dairy',
        ),
        migrations.DeleteModel(
            name='Fruit',
        ),
        migrations.DeleteModel(
            name='Grocery',
        ),
        migrations.DeleteModel(
            name='Vegetable',
        ),
    ]
